### ISSUE TITLE
CSS 实现 Dark Mode 适配

### ISSUE THREAD

**Issue by nusr** [nusr/blog#10]
## 1. CSS + JS 实现 Dark Mode 适配

CSS var 函数可以接受两个参数，第一参数为空时，使用第二个参数。 

[在线例子](https://codepen.io/nusr/pen/JjoNRNB)

```html
<div>
  <div>
   1. CSS + JS 实现 Dark Mode 适配
  </div>
  <label>Light</label>
  <input type="radio" name="theme"      value="day" checked onclick="handleClick(this)"/>
   <label>Dark</label>
  <input type="radio" name="theme" value="dark" onclick="handleClick(this)"/>
</div>
<script>
  function handleClick(e) {
	if (e.value === 'day'){
           document.documentElement.classList.remove('dark');
	}
	else{
           document.documentElement.classList.add('dark');	
	}
}
</script>
```

```css
.dark{
  --background-color: #000;
   --text-color: #fff;
}

body{
  color: var(--text-color,#000);
  background: var(--background-color,#fff);
  transition: all 2s ease-out;
}
```

CSS var 的兼容性如下：

<img width="1260" alt="屏幕快照 2019-12-22 下午5 32 44" src="https://user-images.githubusercontent.com/12200340/71320051-1d894b80-24e1-11ea-98ed-22dc8e2cf252.png">

大部分情况都可以适用，但是要兼容 IE，就不用考虑这个方法了。

## 纯 CSS 实现

**prefers-color-scheme** 可以判断系统使用的主题。

```css
body {
  background-color: #fff；
}
@media (prefers-color-scheme: dark) {
  body {
    background-color: #000；
  }
}
```
**prefers-color-scheme** 的兼容性如下：

<img width="1260" alt="屏幕快照 2019-12-22 下午5 32 12" src="https://user-images.githubusercontent.com/12200340/71320052-25e18680-24e1-11ea-9c08-43552e57d82c.png">

兼容性不如 CSS var，但是不需要使用JS，效率会很高。

## 参考

1. [https://developer.mozilla.org/en-US/docs/Web/CSS/var](https://developer.mozilla.org/en-US/docs/Web/CSS/var)
